# build and commit the dist folder after successful CI
name: CI build

on:
  check_run:
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: ${{ github.event.check_run.name == 'CI' && github.event.check_run.check_suite.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      # build dist folder
      - run: yarn install --frozen-lockfile
      - run: yarn build

      # NOTE: doesn't work if `git add dist --force` is removed
      - run: git add dist --force
      - run: git status

      # commit and push dist folder
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: CI build
          file_pattern: dist
          add_options: '--force'
