# CI for src folder
name: CI

on:
  pull_request:
    branches:
      - '**'
    paths:
      - 'test/**'
      - 'src/**'
      - 'config/**'
      # - '.github/**'
      - 'package.json'
      - 'yarn.lock'
  push:
    branches:
      - '**'
    paths:
      - 'test/**'
      - 'src/**'
      - 'config/**'
      - '.github/**'
      - 'package.json'
      - 'yarn.lock'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    strategy:
      matrix:
        os:
          - ubuntu-22.04

    steps:
      - run: sudo apt install -y xvfb
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22

      - run: yarn install --frozen-lockfile
      - run: yarn test --pool=forks # --pool=forks fixes "Segmentation fault" error in CI
      - run: yarn build

      # disable hosts we shouldn't use
      - run: sudo echo "255.255.255.255 cloudflare-ipfs.com" | sudo tee -a /etc/hosts
      - run: sudo echo "255.255.255.255 pubsubprovider.xyz" | sudo tee -a /etc/hosts

      - run: yarn test:server & yarn test:server:wait-on
      - run: yarn test:e2e:mock
      - run: DEBUG="plebbit-js:*,plebbit-react-hooks:*" yarn test:e2e:chrome
      - run: DEBUG="plebbit-js:*,plebbit-react-hooks:*" yarn test:e2e:firefox
      - run: yarn test:e2e:mock-content
